#! /usr/bin/env bash

main()
{
    ./cs231n/scripts/viz_annotated_im > /dev/null

    ./cs231n/scripts/plot_log vanilla 0
    ./cs231n/scripts/plot_log vanilla 30

    ./cs231n/scripts/plot_log robust 0
    ./cs231n/scripts/plot_log robust 30

    ./cs231n/scripts/plot_maps vanilla 5
    ./cs231n/scripts/plot_maps both 5

    ./cs231n/scripts/plot_maps vanilla 59
    ./cs231n/scripts/plot_maps both 59
}

main
